 ## *Download all CV files (Google Drive links) from the Excel shee*

In [2]:
'''# ============================================================

# Run this in Google Colab
# ============================================================

# 1. Install/upgrade needed packages (requests is left alone -- Colab
#    already ships a compatible version, and upgrading it can trigger
#    dependency-conflict warnings with google-colab's own tools)
!pip install -q --upgrade openpyxl

import re
import os
import openpyxl
import requests

# ------------------------------------------------------------
# 2. Upload the Excel file (skip this cell if you already
#    uploaded it to Colab's file browser on the left)
# ------------------------------------------------------------
from google.colab import files
uploaded = files.upload()   # choose your .xlsx file when prompted
EXCEL_PATH = list(uploaded.keys())[0]

# ------------------------------------------------------------
# 3. Create the output folder named "CVs" using an ABSOLUTE path
#    (so we always know exactly where files land)
# ------------------------------------------------------------
OUTPUT_FOLDER = "/content/CVs"
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# ------------------------------------------------------------
# 4. Read the Excel file and collect (Name, Drive link) pairs
#    Sheet columns: Full Name | University | CV | standard_univ
# ------------------------------------------------------------
wb = openpyxl.load_workbook(EXCEL_PATH, data_only=True)
ws = wb.worksheets[0]  # first sheet

rows = list(ws.iter_rows(min_row=2, values_only=True))  # skip header row

entries = []
for row in rows:
    name = row[0]
    link = row[2]  # "CV" column
    if name and link and "drive.google.com" in str(link):
        entries.append((str(name).strip(), str(link).strip()))

print(f"Found {len(entries)} CV links to download.")

# ------------------------------------------------------------
# 5. Extract the Google Drive file ID from any link format
# ------------------------------------------------------------
def extract_file_id(url: str):
    patterns = [
        r"/d/([a-zA-Z0-9_-]+)",
        r"id=([a-zA-Z0-9_-]+)",
    ]
    for pat in patterns:
        m = re.search(pat, url)
        if m:
            return m.group(1)
    return None

def safe_filename(name: str) -> str:
    return re.sub(r'[\\/*?:"<>|]', "", name).strip()

# ------------------------------------------------------------
# 6. Robust download function using requests directly.
#    Handles Google's "can't scan large file for viruses"
#    confirmation page, which is what silently breaks gdown
#    in a lot of Colab sessions.
# ------------------------------------------------------------
def download_drive_file(file_id: str, dest_path_no_ext: str, session: requests.Session):
    URL = "https://drive.google.com/uc?export=download"
    response = session.get(URL, params={"id": file_id}, stream=True)

    # Look for a confirm token (appears for large files)
    token = None
    for key, value in response.cookies.items():
        if key.startswith("download_warning"):
            token = value
            break

    if token is None:
        # Some responses embed the confirm token in the HTML instead of cookies
        if "text/html" in response.headers.get("Content-Type", ""):
            match = re.search(r"confirm=([0-9A-Za-z_-]+)", response.text)
            if match:
                token = match.group(1)

    if token:
        response = session.get(URL, params={"id": file_id, "confirm": token}, stream=True)

    content_type = response.headers.get("Content-Type", "")
    content_disp = response.headers.get("Content-Disposition", "")

    # Figure out a reasonable extension
    ext = ".pdf"  # sensible default for CVs
    m = re.search(r'filename="?([^";]+)"?', content_disp)
    if m:
        original_name = m.group(1)
        if "." in original_name:
            ext = "." + original_name.rsplit(".", 1)[-1]

    dest_path = dest_path_no_ext + ext

    if "text/html" in content_type:
        # We got an HTML page, not the actual file -> download failed
        return None

    with open(dest_path, "wb") as f:
        for chunk in response.iter_content(chunk_size=32768):
            if chunk:
                f.write(chunk)

    # Sanity check: make sure the file isn't suspiciously tiny (likely an error page)
    if os.path.getsize(dest_path) < 1024:
        with open(dest_path, "rb") as f:
            head = f.read(200).lower()
        if b"<html" in head or b"<!doctype" in head:
            os.remove(dest_path)
            return None

    return dest_path

# ------------------------------------------------------------
# 7. Download each file into the CVs folder
# ------------------------------------------------------------
failed = []
succeeded = []
session = requests.Session()

for i, (name, link) in enumerate(entries, start=1):
    file_id = extract_file_id(link)
    if not file_id:
        print(f"[{i}/{len(entries)}] Could not parse file ID for {name}: {link}")
        failed.append((name, link))
        continue

    dest_prefix = os.path.join(OUTPUT_FOLDER, safe_filename(name))
    try:
        result_path = download_drive_file(file_id, dest_prefix, session)
        if result_path:
            size_kb = os.path.getsize(result_path) / 1024
            print(f"[{i}/{len(entries)}] OK: {os.path.basename(result_path)} ({size_kb:.1f} KB)")
            succeeded.append((name, result_path))
        else:
            print(f"[{i}/{len(entries)}] FAILED (file not public or blocked) for {name}")
            failed.append((name, link))
    except Exception as e:
        print(f"[{i}/{len(entries)}] FAILED for {name}: {e}")
        failed.append((name, link))

# ------------------------------------------------------------
# 8. VERIFY what's actually on disk (don't trust the log alone)
# ------------------------------------------------------------
actual_files = os.listdir(OUTPUT_FOLDER)
print("\n" + "=" * 60)
print(f"Verified: {len(actual_files)} file(s) physically present in {OUTPUT_FOLDER}")
print("=" * 60)
for f in actual_files:
    full = os.path.join(OUTPUT_FOLDER, f)
    print(f" - {f}  ({os.path.getsize(full)/1024:.1f} KB)")

if failed:
    print(f"\n{len(failed)} file(s) failed to download (likely not shared as 'Anyone with the link'):")
    for name, link in failed:
        print(f" - {name}: {link}")

# ------------------------------------------------------------
# 9. Zip the CVs folder and download it to your computer
#    (Only run this after confirming the file count above looks right.
#     Also remember: refresh the Colab file browser panel on the left
#     with the circular-arrow icon -- it does NOT auto-refresh.)
# ------------------------------------------------------------
!cd /content && zip -r CVs.zip CVs
files.download("/content/CVs.zip")'''

'# ============================================================\n\n# Run this in Google Colab\n# ============================================================\n\n# 1. Install/upgrade needed packages (requests is left alone -- Colab\n#    already ships a compatible version, and upgrading it can trigger\n#    dependency-conflict warnings with google-colab\'s own tools)\n!pip install -q --upgrade openpyxl\n\nimport re\nimport os\nimport openpyxl\nimport requests\n\n# ------------------------------------------------------------\n# 2. Upload the Excel file (skip this cell if you already\n#    uploaded it to Colab\'s file browser on the left)\n# ------------------------------------------------------------\nfrom google.colab import files\nuploaded = files.upload()   # choose your .xlsx file when prompted\nEXCEL_PATH = list(uploaded.keys())[0]\n\n# ------------------------------------------------------------\n# 3. Create the output folder named "CVs" using an ABSOLUTE path\n#    (so we always know exactly where files land)\n# ------------------------------------------------------------\nOUTPUT_FOLDER = "/content/CVs"\nos.makedirs(OUTPUT_FOLDER, exist_ok=True)\n\n# ------------------------------------------------------------\n# 4. Read the Excel file and collect (Name, Drive link) pairs\n#    Sheet columns: Full Name | University | CV | standard_univ\n# ------------------------------------------------------------\nwb = openpyxl.load_workbook(EXCEL_PATH, data_only=True)\nws = wb.worksheets[0]  # first sheet\n\nrows = list(ws.iter_rows(min_row=2, values_only=True))  # skip header row\n\nentries = []\nfor row in rows:\n    name = row[0]\n    link = row[2]  # "CV" column\n    if name and link and "drive.google.com" in str(link):\n        entries.append((str(name).strip(), str(link).strip()))\n\nprint(f"Found {len(entries)} CV links to download.")\n\n# ------------------------------------------------------------\n# 5. Extract the Google Drive file ID from any link format\n# ------------------------------------------------------------\ndef extract_file_id(url: str):\n    patterns = [\n        r"/d/([a-zA-Z0-9_-]+)",\n        r"id=([a-zA-Z0-9_-]+)",\n    ]\n    for pat in patterns:\n        m = re.search(pat, url)\n        if m:\n            return m.group(1)\n    return None\n\ndef safe_filename(name: str) -> str:\n    return re.sub(r\'[\\/*?:"<>|]\', "", name).strip()\n\n# ------------------------------------------------------------\n# 6. Robust download function using requests directly.\n#    Handles Google\'s "can\'t scan large file for viruses"\n#    confirmation page, which is what silently breaks gdown\n#    in a lot of Colab sessions.\n# ------------------------------------------------------------\ndef download_drive_file(file_id: str, dest_path_no_ext: str, session: requests.Session):\n    URL = "https://drive.google.com/uc?export=download"\n    response = session.get(URL, params={"id": file_id}, stream=True)\n\n    # Look for a confirm token (appears for large files)\n    token = None\n    for key, value in response.cookies.items():\n        if key.startswith("download_warning"):\n            token = value\n            break\n\n    if token is None:\n        # Some responses embed the confirm token in the HTML instead of cookies\n        if "text/html" in response.headers.get("Content-Type", ""):\n            match = re.search(r"confirm=([0-9A-Za-z_-]+)", response.text)\n            if match:\n                token = match.group(1)\n\n    if token:\n        response = session.get(URL, params={"id": file_id, "confirm": token}, stream=True)\n\n    content_type = response.headers.get("Content-Type", "")\n    content_disp = response.headers.get("Content-Disposition", "")\n\n    # Figure out a reasonable extension\n    ext = ".pdf"  # sensible default for CVs\n    m = re.search(r\'filename="?([^";]+)"?\', content_disp)\n    if m:\n        original_name = m.group(1)\n        if "." in original_name:\n            ext = "." + original_name.rsplit(".", 1)[-1]\n\n    dest_path = dest_path_no_ext + ext\n\n    if "text/html" in content_type:\n        # We got an HTML page, not the actual file -> download failed\n        return None\n\n    with open(dest_path, "wb") as f:\n        for chunk in response.iter_content(chunk_size=32768):\n            if chunk:\n                f.write(chunk)\n\n    # Sanity check: make sure the file isn\'t suspiciously tiny (likely an error page)\n    if os.path.getsize(dest_path) < 1024:\n        with open(dest_path, "rb") as f:\n            head = f.read(200).lower()\n        if b"<html" in head or b"<!doctype" in head:\n            os.remove(dest_path)\n            return None\n\n    return dest_path\n\n# ------------------------------------------------------------\n# 7. Download each file into the CVs folder\n# ------------------------------------------------------------\nfailed = []\nsucceeded = []\nsession = requests.Session()\n\nfor i, (name, link) in enumerate(entries, start=1):\n    file_id = extract_file_id(link)\n    if not file_id:\n        print(f"[{i}/{len(entries)}] Could not parse file ID for {name}: {link}")\n        failed.append((name, link))\n        continue\n\n    dest_prefix = os.path.join(OUTPUT_FOLDER, safe_filename(name))\n    try:\n        result_path = download_drive_file(file_id, dest_prefix, session)\n        if result_path:\n            size_kb = os.path.getsize(result_path) / 1024\n            print(f"[{i}/{len(entries)}] OK: {os.path.basename(result_path)} ({size_kb:.1f} KB)")\n            succeeded.append((name, result_path))\n        else:\n            print(f"[{i}/{len(entries)}] FAILED (file not public or blocked) for {name}")\n            failed.append((name, link))\n    except Exception as e:\n        print(f"[{i}/{len(entries)}] FAILED for {name}: {e}")\n        failed.append((name, link))\n\n# ------------------------------------------------------------\n# 8. VERIFY what\'s actually on disk (don\'t trust the log alone)\n# ------------------------------------------------------------\nactual_files = os.listdir(OUTPUT_FOLDER)\nprint("\n" + "=" * 60)\nprint(f"Verified: {len(actual_files)} file(s) physically present in {OUTPUT_FOLDER}")\nprint("=" * 60)\nfor f in actual_files:\n    full = os.path.join(OUTPUT_FOLDER, f)\n    print(f" - {f}  ({os.path.getsize(full)/1024:.1f} KB)")\n\nif failed:\n    print(f"\n{len(failed)} file(s) failed to download (likely not shared as \'Anyone with the link\'):")\n    for name, link in failed:\n        print(f" - {name}: {link}")\n\n# ------------------------------------------------------------\n# 9. Zip the CVs folder and download it to your computer\n#    (Only run this after confirming the file count above looks right.\n#     Also remember: refresh the Colab file browser panel on the left\n#     with the circular-arrow icon -- it does NOT auto-refresh.)\n# ------------------------------------------------------------\n!cd /content && zip -r CVs.zip CVs\nfiles.download("/content/CVs.zip")'

In [ ]:
""" from google.colab import drive
drive.mount('/content/drive')

cv_folder = '/content/drive/MyDrive/CVs'  """

Mounted at /content/drive

In [3]:
from google.colab import drive
drive.mount('/content/drive')

import os
import zipfile
import shutil

cv_folder = '/content/CVs'
os.makedirs(cv_folder, exist_ok=True)

zip_path = '/content/CVs.zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    for file in zip_ref.namelist():

        # Ignore folders
        if file.endswith('/'):
            continue

        # Get only the filename
        filename = os.path.basename(file)

        # Skip hidden/system files
        if filename.startswith('.') or not filename:
            continue

        # Extract directly into /content/CVs
        destination = os.path.join(cv_folder, filename)

        with zip_ref.open(file) as source, open(destination, 'wb') as target:
            shutil.copyfileobj(source, target)

print("All CVs extracted successfully!")

# Count CV files
cv_files = [
    f for f in os.listdir(cv_folder)
    if f.lower().endswith(('.pdf', '.docx', '.doc'))
]

print(f"Total CVs found: {len(cv_files)}")

for cv in cv_files:
    print(cv)

Mounted at /content/drive
All CVs extracted successfully!
Total CVs found: 98
Hamza Ali Bakr.docx
Ahmed Osama.pdf
Moataz Badawy.pdf
Hassan Hossam eldain hassan.docx
Abdallah Yahia Mansour Mohammed.pdf
Bassel Hesham Farouk.pdf
Abdelrahman Amr.pdf
Mohamed Hisham Wafa.docx
Youssef Mohamed Kenawy.pdf
Ziad Basem El Gamal.pdf
Loai Farrag.docx
Yassin Mohamed Amer.docx
Omar tamer momtaz.pdf
Omar Ahmed Abdelraouf.pdf
Sally Ahmed Mostafa Mohamed.pdf
Marwan sherif saleh.pdf
Habiba Ahmed Aboelenen.pdf
Noor Omar Mohamed Elsamahy.docx
Karim Mohamed Abdelaziz Mokadem.pdf
Maria Ashraf.pdf
Malak Ahmed.pdf
Alaa Karam Ahmed Mohamed Salama.pdf
Abdelrahaman ehab.docx
Omar hazem algaradawy.pdf
Andrew Refaat.pdf
Moustafa Hani Moustafa Mansour.pdf
sylvia faris wardkhan.pdf
Khaled Ehab Abdelfattah.pdf
Ahmed Maged Mounir Mohammed.pdf
Natalia Ehab Habib.pdf
Mahmoud Samir Mahmoud Moustafa.pdf
Yehia Mohamed Mohamed Alsaeed.pdf
Hassan Mohammed Wael aburezq.pdf
Yassin Saleh Ahmed.pdf
Yousef Elbrolosy.pdf
nourhan mohamed.pdf
Ather Walid Abdel Wahed Abou Shama.pdf
Nourine Hossam el deen mokhtar.pdf
Youssof Hossam ELdin Fawzy.pdf
Mariam Ahmed Bolbol.pdf
Hazem Ismail Ismail Mostafa Zidan.pdf
Abdelrahman Mahmoud Almakhzangy.pdf
Omar Raafat Eleraky.pdf
Raghad Mohamed Wael Khalil.pdf
Sherry Nabil Mahmoud.pdf
Omar sherif Tolba.pdf
Sarah Tawfik.pdf
Reem Mohamed Ibrahim.pdf
Nada Aly.docx
Elsayed Ayman Elsayed.pdf
mariam hatem.pdf
Andrew Aziz.pdf
Abdelrahman Mohamed Elkady.pdf
Marwan ahmed.pdf
Reham Sameh Sayed Kandeel.pdf
Hazim Ashraf.pdf
Omar Wael Hassan.pdf
Mohamed Mokhtar Shaker.pdf
Sondos Belal Elahmady.pdf
Abdelrahman Osama Abdelhamid Mohamed Aly.pdf
Moaz Eslam Salah NourEldin.pdf
Kareem Abdellatif.pdf
Faten Shahir Shokry Negeida.pdf
Fatima Alzhraa Mahmoud Elemam.pdf
Youssef Hussien Rady.pdf
Youssef abdelmesseh ramzy.pdf
Nour mohamed hassan.pdf
Youssef abdulazim.pdf
Zeyad Hesham Mohamed Hussein.pdf
Mohanad tamer sabry.pdf
joumana nour hozayen.pdf
Omar Mohamed.pdf
ahmed mohamed ezzat.pdf
Youssef Mohammed Hussein sayed abdelalim.pdf
Jomana Gehad Mohamed.docx
Yusuf Adel Abbas Amin.pdf
Marwa Ahmed Yehia Ibrahem.pdf
Mohamed Alhusein Abdalla.pdf
Laila Bassem.pdf
Bilal mohamed fathy elbably eid.pdf
Omar Ibraheem Fekry.pdf
Sondos Osama Hanafi Madboly Ibrahim.pdf
Marwan Montasser Morad Hassan.pdf
Hana hatem.pdf
Sama Mostafa kamel.pdf
Seif Ahmed Ibrahim Eltahmoudi.pdf
Mohamed Ahmed Mohamed Abdelsamie Arid.pdf
Malak Emad Mohamed.pdf
Habiba Tarek Maher.pdf
Khaled Mahmoud Hamdi.pdf
Sara sharkawy.pdf
Amr karam alaasar.pdf
Doaa Farhat Shaban Hassan.pdf
Salma Taha Abdelalem Eloraby.pdf
Shahd ismail.pdf
Mirna Hany.pdf
Maged waleed.pdf
Abdulrahman wahba.pdf

In [4]:
!pip install pymupdf python-docx pytesseract sentence-transformers scikit-learn pandas pillow
!apt-get install -y tesseract-ocr

Collecting pymupdf
  Downloading pymupdf-1.28.2-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (26 kB)
Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (11.3.0)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.1.1)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.16.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (26.2)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.23.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading pymupdf-1.28.2-cp310-abi3-manylinux_2_28_x86_64.whl (25.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 57.3 MB/s eta 0:00:00
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 6.9 MB/s eta 0:00:00
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Installing collected packages: python-docx, pytesseract, pymupdf
Successfully installed pymupdf-1.28.2 pytesseract-0.3.13 python-docx-1.2.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import fitz  # PyMuPDF
import docx
import pytesseract
from PIL import Image
import os

def extract_text(filepath):
    ext = filepath.lower().split('.')[-1]
    text = ""

    if ext == 'pdf':
        doc = fitz.open(filepath)
        for page in doc:
            text += page.get_text()
        doc.close()

    elif ext == 'docx':
        d = docx.Document(filepath)
        text = "\n".join([p.text for p in d.paragraphs])

    elif ext == 'png':
        img = Image.open(filepath)
        text = pytesseract.image_to_string(img)

    return text.strip()

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

In [7]:
cv_texts = {}

for filename in os.listdir(cv_folder):
    filepath = os.path.join(cv_folder, filename)
    try:
        text = extract_text(filepath)
        if text:  # skip empty extractions
            cv_texts[filename] = text
    except Exception as e:
        print(f"Failed to read {filename}: {e}")

print(f"Successfully extracted {len(cv_texts)} CVs")

Successfully extracted 97 CVs

# AI CV Job Matching System

The original Google Drive CV downloader is preserved above. The matching pipeline below is designed for the AI Internship criteria and supports 100+ CVs.

It combines rule-based skill matching, semantic similarity, evidence scoring, and an AI/domain relevance gate.

## 1. Install Dependencies

In [8]:
!pip install -q pymupdf python-docx sentence-transformers scikit-learn pandas openpyxl tqdm

## 2. Import Libraries and Configure the Pipeline

In [9]:
import os
import re
import numpy as np
import pandas as pd
import fitz
import docx
from tqdm.auto import tqdm
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

CV_FOLDER = "/content/CVs"

# Final-score weights. Easy to change.
KEYWORD_WEIGHT = 0.35
SEMANTIC_WEIGHT = 0.35
EVIDENCE_WEIGHT = 0.30

# Unrelated CVs below this AI/technical relevance level are rejected.
AI_RELEVANCE_THRESHOLD = 0.20

TOP_N = 20

def decision_from_score(score):
    if score == 0:
        return "REJECT"
    if score >= 90:
        return "EXCELLENT MATCH"
    if score >= 75:
        return "STRONG MATCH"
    if score >= 60:
        return "GOOD MATCH"
    if score >= 10:
        return "WEAK MATCH"
    return "VERY WEAK MATCH"

print("Configuration loaded.")

Configuration loaded.

## 3. Extract and Clean CV Text

In [10]:
def extract_pdf_text(filepath):
    parts = []
    with fitz.open(filepath) as pdf:
        for page in pdf:
            parts.append(page.get_text())
    return "\n".join(parts).strip()

def extract_docx_text(filepath):
    document = docx.Document(filepath)
    parts = [p.text for p in document.paragraphs if p.text.strip()]
    for table in document.tables:
        for row in table.rows:
            parts.append(" ".join(cell.text for cell in row.cells if cell.text.strip()))
    return "\n".join(parts).strip()

def extract_txt_text(filepath):
    with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
        return f.read().strip()

def extract_text(filepath):
    ext = os.path.splitext(filepath)[1].lower()
    if ext == ".pdf":
        return extract_pdf_text(filepath)
    if ext == ".docx":
        return extract_docx_text(filepath)
    if ext == ".txt":
        return extract_txt_text(filepath)
    raise ValueError(f"Unsupported file type: {ext}")

def clean_text(text):
    text = str(text).lower()
    text = text.replace("\x00", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

cv_records = []

if not os.path.isdir(CV_FOLDER):
    raise FileNotFoundError(f"CV folder not found: {CV_FOLDER}")

for filename in sorted(os.listdir(CV_FOLDER)):
    filepath = os.path.join(CV_FOLDER, filename)
    if not os.path.isfile(filepath):
        continue

    ext = os.path.splitext(filename)[1].lower()
    if ext not in {".pdf", ".docx", ".txt"}:
        continue

    try:
        raw_text = extract_text(filepath)
        candidate_name = os.path.splitext(filename)[0]

        if not raw_text.strip():
            status = "EMPTY"
            raw_text = ""
        else:
            status = "OK"

        cv_records.append({
            "filename": filename,
            "filepath": filepath,
            "candidate_name": candidate_name,
            "full_text": raw_text,
            "clean_text": clean_text(raw_text),
            "file_type": ext.replace(".", "").upper(),
            "processing_status": status
        })

    except Exception as e:
        cv_records.append({
            "filename": filename,
            "filepath": filepath,
            "candidate_name": os.path.splitext(filename)[0],
            "full_text": "",
            "clean_text": "",
            "file_type": ext.replace(".", "").upper(),
            "processing_status": f"ERROR: {str(e)[:150]}"
        })

cv_df = pd.DataFrame(cv_records)

print(f"Found {len(cv_df)} supported CV file(s).")
if len(cv_df):
    print(cv_df["processing_status"].value_counts(dropna=False))

Found 98 supported CV file(s).
processing_status
OK       97
EMPTY     1
Name: count, dtype: int64

## 4. Define AI Internship Requirements

In [11]:
JOB_REQUIREMENTS = {
    "ml_fundamentals": {
        "name": "ML Fundamentals",
        "weight": 0.20,
        "description": "Strong understanding of Machine Learning fundamentals.",
        "keywords": [
            "machine learning", "ml", "supervised learning",
            "unsupervised learning", "classification", "regression",
            "clustering", "feature engineering", "model selection"
        ]
    },
    "model_training_evaluation": {
        "name": "Model Training / Evaluation / Optimization",
        "weight": 0.20,
        "description": "Experience training, evaluating, and optimizing Machine Learning models.",
        "keywords": [
            "model training", "training models", "model evaluation",
            "evaluation", "optimization", "hyperparameter tuning",
            "cross validation", "cross-validation", "accuracy",
            "precision", "recall", "f1 score", "f1-score", "roc auc"
        ]
    },
    "ai_projects": {
        "name": "Hands-on AI Projects",
        "weight": 0.20,
        "description": "Hands-on AI projects such as Chatbots, NLP, or Computer Vision.",
        "keywords": [
            "artificial intelligence", "ai project", "ai projects",
            "chatbot", "chatbots", "nlp", "natural language processing",
            "sentiment analysis", "text classification", "language model",
            "computer vision", "opencv", "image classification",
            "object detection", "image processing"
        ]
    },
    "backend": {
        "name": "Backend Development",
        "weight": 0.10,
        "description": "Good understanding of Backend Development concepts.",
        "keywords": [
            "backend", "back-end", "server-side", "backend development",
            "server development"
        ]
    },
    "rest_api": {
        "name": "REST APIs / FastAPI / Flask",
        "weight": 0.15,
        "description": "Experience working with REST APIs, preferably FastAPI or Flask.",
        "keywords": [
            "rest api", "restful api", "api development",
            "fastapi", "fast api", "flask", "api"
        ]
    },
    "deployment": {
        "name": "AI Model Integration / Deployment",
        "weight": 0.15,
        "description": "Experience integrating and deploying AI models through APIs in real-world applications.",
        "keywords": [
            "model deployment", "ml deployment", "ai deployment",
            "model serving", "deployment", "deployed model",
            "model integration", "ai integration", "api integration",
            "production", "docker"
        ]
    }
}

weight_sum = sum(x["weight"] for x in JOB_REQUIREMENTS.values())
for x in JOB_REQUIREMENTS.values():
    x["normalized_weight"] = x["weight"] / weight_sum

JOB_DESCRIPTION = "\n".join(
    f"{x['name']}: {x['description']}"
    for x in JOB_REQUIREMENTS.values()
)

print(JOB_DESCRIPTION)

ML Fundamentals: Strong understanding of Machine Learning fundamentals.
Model Training / Evaluation / Optimization: Experience training, evaluating, and optimizing Machine Learning models.
Hands-on AI Projects: Hands-on AI projects such as Chatbots, NLP, or Computer Vision.
Backend Development: Good understanding of Backend Development concepts.
REST APIs / FastAPI / Flask: Experience working with REST APIs, preferably FastAPI or Flask.
AI Model Integration / Deployment: Experience integrating and deploying AI models through APIs in real-world applications.

## 5. AI / Technical Relevance Gate

In [12]:
AI_RELEVANCE_GROUPS = {
    "ai_ml": [
        "artificial intelligence", "machine learning", "deep learning",
        "neural network", "neural networks", "nlp",
        "natural language processing", "computer vision",
        "model training", "model evaluation", "scikit-learn",
        "tensorflow", "pytorch", "xgboost"
    ],
    "ai_projects": [
        "chatbot", "sentiment analysis", "object detection",
        "image classification", "text classification",
        "recommendation system", "recommendation engine",
        "generative ai", "genai", "llm"
    ],
    "technical_backend": [
        "python", "fastapi", "flask", "rest api",
        "restful api", "backend", "backend development",
        "api development", "model deployment", "model serving"
    ]
}

def count_group_hits(text, phrases):
    return sum(
        1 for phrase in phrases
        if re.search(r"\b" + re.escape(phrase.lower()) + r"\b", text)
    )

def calculate_ai_relevance(text):
    """
    AI relevance = actual match against the AI internship requirements.

    Each requirement is weighted according to JOB_REQUIREMENTS.
    This is the score that should be used for ranking candidates.
    """

    if not text:
        return 0.0

    requirement_scores = {}

    for req_key, req in JOB_REQUIREMENTS.items():

        keyword_score, matched_keywords = calculate_keyword_score(
            text,
            req
        )

        # If there is no actual keyword evidence,
        # don't allow semantic similarity alone to make the
        # candidate look highly relevant.
        if not matched_keywords:
            requirement_scores[req_key] = 0.0
            continue

        requirement_scores[req_key] = keyword_score

    # Weighted AI job relevance
    ai_relevance = sum(
        requirement_scores[key] *
        JOB_REQUIREMENTS[key]["normalized_weight"]
        for key in JOB_REQUIREMENTS
    )

    return float(min(max(ai_relevance, 0.0), 1.0))

BASE_ON_FIRST_MATCH = 0.6
BONUS_PER_EXTRA_MATCH = 0.15
MAX_EXTRA_MATCHES_COUNTED = int((1.0 - BASE_ON_FIRST_MATCH) / BONUS_PER_EXTRA_MATCH)

def calculate_keyword_score(text, requirement):
    if not text:
        return 0.0, []
    text = clean_text(text)
    matched = []
    for kw in requirement["keywords"]:
        pattern = r"\b" + re.escape(kw.lower()) + r"\b"
        if re.search(pattern, text):
            matched.append(kw)
    matched = list(dict.fromkeys(matched))  # dedupe, keep order
    if not matched:
        return 0.0, matched
    extra = min(len(matched) - 1, MAX_EXTRA_MATCHES_COUNTED)
    score = min(BASE_ON_FIRST_MATCH + extra * BONUS_PER_EXTRA_MATCH, 1.0)
    return float(score), matched



def evidence_snippet(text, matched_terms, max_chars=300):
    if not text or not matched_terms:
        return "Not Found"

    text_clean = re.sub(r"\s+", " ", text).strip()

    for term in matched_terms:
        idx = text_clean.lower().find(term.lower())
        if idx >= 0:
            start = max(0, idx - 100)
            end = min(len(text_clean), idx + max_chars)
            return text_clean[start:end]

    return "Not Found"

## 6. Load Sentence Transformer Model

In [13]:
model = SentenceTransformer("all-MiniLM-L6-v2")

requirement_items = list(JOB_REQUIREMENTS.items())
requirement_texts = [x["description"] for _, x in requirement_items]

requirement_embeddings = model.encode(
    requirement_texts,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

print("Semantic model loaded once.")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Semantic model loaded once.

## 7. Score Every Candidate

In [14]:
valid_mask = (
    cv_df["processing_status"].eq("OK") &
    cv_df["clean_text"].str.len().gt(0)
)

valid_indices = cv_df.index[valid_mask].tolist()
candidate_texts = cv_df.loc[valid_indices, "clean_text"].tolist()

if candidate_texts:
    candidate_embeddings = model.encode(
        candidate_texts,
        convert_to_numpy=True,
        normalize_embeddings=True,
        batch_size=32,
        show_progress_bar=True
    )
else:
    candidate_embeddings = np.empty((0, requirement_embeddings.shape[1]))

results = []

for pos, idx in enumerate(tqdm(valid_indices, desc="Scoring CVs")):
    row = cv_df.loc[idx]
    text = row["clean_text"]

    ai_relevance = calculate_ai_relevance(text)

    keyword_scores = {}
    semantic_scores = {}
    evidence_scores = {}
    matched_skills = []
    missing_skills = []
    evidence = {}

    for req_pos, (req_key, req) in enumerate(requirement_items):
        k_score, matched = calculate_keyword_score(text, req)

        semantic = float(
            cosine_similarity(
                [candidate_embeddings[pos]],
                [requirement_embeddings[req_pos]]
            )[0][0]
        )
        semantic = max(0.0, min(1.0, semantic))

        evidence_score = min(
            1.0,
            0.70 * k_score + 0.30 * (1.0 if matched else 0.0)
        )

        keyword_scores[req_key] = k_score
        semantic_scores[req_key] = semantic
        evidence_scores[req_key] = evidence_score

        if matched:
            matched_skills.extend(matched)
            evidence[req["name"]] = evidence_snippet(text, matched)
        else:
            missing_skills.append(req["name"])
            evidence[req["name"]] = "Not Found"

    keyword_total = sum(
        keyword_scores[k] * JOB_REQUIREMENTS[k]["normalized_weight"]
        for k in JOB_REQUIREMENTS
    )
    semantic_total = sum(
        semantic_scores[k] * JOB_REQUIREMENTS[k]["normalized_weight"]
        for k in JOB_REQUIREMENTS
    )
    evidence_total = sum(
        evidence_scores[k] * JOB_REQUIREMENTS[k]["normalized_weight"]
        for k in JOB_REQUIREMENTS
    )

    base_score = (
        KEYWORD_WEIGHT * keyword_total +
        SEMANTIC_WEIGHT * semantic_total +
        EVIDENCE_WEIGHT * evidence_total
    )

    if ai_relevance < AI_RELEVANCE_THRESHOLD:
        final_score = 0.0
        decision = "REJECT"
    else:
        final_score = round(base_score * 100, 2)
        decision = decision_from_score(final_score)

    result = {
        "candidate_name": row["candidate_name"],
        "filename": row["filename"],
        "file_type": row["file_type"],
        "processing_status": row["processing_status"],
        "ai_relevance_percent": round(ai_relevance * 100, 2),
        "keyword_percent": round(keyword_total * 100, 2),
        "semantic_percent": round(semantic_total * 100, 2),
        "evidence_percent": round(evidence_total * 100, 2),
        "final_match_percent": final_score,
        "decision": decision,
        "matched_skills": ", ".join(sorted(set(matched_skills))),
        "missing_skills": ", ".join(missing_skills),
        "strong_evidence": " | ".join(
            f"{k}: {v}" for k, v in evidence.items() if v != "Not Found"
        ) or "Not Found"
    }

    for req_key, req in JOB_REQUIREMENTS.items():
        result[f"{req['name']} - Keyword"] = round(
            keyword_scores[req_key] * 100, 2
        )
        result[f"{req['name']} - Semantic"] = round(
            semantic_scores[req_key] * 100, 2
        )
        result[f"{req['name']} - Evidence"] = round(
            evidence_scores[req_key] * 100, 2
        )

    results.append(result)

# Preserve empty/error CVs in the final report.
for idx in cv_df.index[~valid_mask]:
    row = cv_df.loc[idx]
    result = {
        "candidate_name": row["candidate_name"],
        "filename": row["filename"],
        "file_type": row["file_type"],
        "processing_status": row["processing_status"],
        "ai_relevance_percent": 0.0,
        "keyword_percent": 0.0,
        "semantic_percent": 0.0,
        "evidence_percent": 0.0,
        "final_match_percent": 0.0,
        "decision": "REJECT - FILE ERROR/EMPTY",
        "matched_skills": "",
        "missing_skills": ", ".join(x["name"] for x in JOB_REQUIREMENTS.values()),
        "strong_evidence": "Not Available"
    }

    for req in JOB_REQUIREMENTS.values():
        result[f"{req['name']} - Keyword"] = 0.0
        result[f"{req['name']} - Semantic"] = 0.0
        result[f"{req['name']} - Evidence"] = 0.0

    results.append(result)

results_df = pd.DataFrame(results)
print(f"Scored {len(results_df)} CVs.")

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Scoring CVs:   0%|          | 0/97 [00:00<?, ?it/s]

Scored 98 CVs.

## 8. Rank Candidates

In [15]:
results_df = results_df.sort_values(
    by=["final_match_percent", "ai_relevance_percent"],
    ascending=False
).reset_index(drop=True)

results_df.insert(0, "rank", np.arange(1, len(results_df) + 1))

preview_cols = [
    "rank", "candidate_name", "filename",
    "ai_relevance_percent", "final_match_percent", "decision"
]

display(results_df[preview_cols].head(TOP_N))

,rank,candidate_name,filename,ai_relevance_percent,final_match_percent,decision
0,1,Omar Mohamed,Omar Mohamed.pdf,81.75,68.97,GOOD MATCH
1,2,Salma Taha Abdelalem Eloraby,Salma Taha Abdelalem Eloraby.pdf,82.50,68.12,GOOD MATCH
2,3,Youssef Mohamed Kenawy,Youssef Mohamed Kenawy.pdf,84.75,67.49,GOOD MATCH
3,4,Hamza Ali Bakr,Hamza Ali Bakr.docx,79.50,65.25,GOOD MATCH
4,5,Marwa Ahmed Yehia Ibrahem,Marwa Ahmed Yehia Ibrahem.pdf,73.50,63.92,GOOD MATCH
5,6,Hazem Ismail Ismail Mostafa Zidan,Hazem Ismail Ismail Mostafa Zidan.pdf,77.25,63.59,GOOD MATCH
6,7,Marwan Montasser Morad Hassan,Marwan Montasser Morad Hassan.pdf,76.50,63.54,GOOD MATCH
7,8,Jomana Gehad Mohamed,Jomana Gehad Mohamed.docx,74.25,62.66,GOOD MATCH
8,9,Loai Farrag,Loai Farrag.docx,80.25,62.05,GOOD MATCH
9,10,Abdelrahman Mohamed Elkady,Abdelrahman Mohamed Elkady.pdf,75.75,61.43,GOOD MATCH
10,11,Raghad Mohamed Wael Khalil,Raghad Mohamed Wael Khalil.pdf,78.00,60.86,GOOD MATCH
11,12,Andrew Aziz,Andrew Aziz.pdf,69.75,58.97,WEAK MATCH
12,13,Abdulrahman wahba,Abdulrahman wahba.pdf,69.00,58.43,WEAK MATCH
13,14,Khaled Mahmoud Hamdi,Khaled Mahmoud Hamdi.pdf,68.25,58.42,WEAK MATCH
14,15,Karim Mohamed Abdelaziz Mokadem,Karim Mohamed Abdelaziz Mokadem.pdf,65.25,57.20,WEAK MATCH
15,16,Maged waleed,Maged waleed.pdf,61.50,57.07,WEAK MATCH
16,17,Marwan sherif saleh,Marwan sherif saleh.pdf,75.00,56.48,WEAK MATCH
17,18,Hazim Ashraf,Hazim Ashraf.pdf,68.25,55.53,WEAK MATCH
18,19,Youssef abdulazim,Youssef abdulazim.pdf,72.75,55.46,WEAK MATCH
19,20,Yusuf Adel Abbas Amin,Yusuf Adel Abbas Amin.pdf,65.25,54.96,WEAK MATCH

## 9. Top Candidates and Rejected Candidates

In [16]:
for n in [5, 10, TOP_N]:
    n = min(n, len(results_df))
    print(f"\nTOP {n}")
    display(results_df[preview_cols].head(n))

rejected_df = results_df[
    results_df["decision"].str.startswith("REJECT")
].copy()

print("\nREJECTED CANDIDATES")
display(rejected_df[preview_cols])

TOP 5

,rank,candidate_name,filename,ai_relevance_percent,final_match_percent,decision
0,1,Omar Mohamed,Omar Mohamed.pdf,81.75,68.97,GOOD MATCH
1,2,Salma Taha Abdelalem Eloraby,Salma Taha Abdelalem Eloraby.pdf,82.50,68.12,GOOD MATCH
2,3,Youssef Mohamed Kenawy,Youssef Mohamed Kenawy.pdf,84.75,67.49,GOOD MATCH
3,4,Hamza Ali Bakr,Hamza Ali Bakr.docx,79.50,65.25,GOOD MATCH
4,5,Marwa Ahmed Yehia Ibrahem,Marwa Ahmed Yehia Ibrahem.pdf,73.50,63.92,GOOD MATCH

TOP 10

,rank,candidate_name,filename,ai_relevance_percent,final_match_percent,decision
0,1,Omar Mohamed,Omar Mohamed.pdf,81.75,68.97,GOOD MATCH
1,2,Salma Taha Abdelalem Eloraby,Salma Taha Abdelalem Eloraby.pdf,82.50,68.12,GOOD MATCH
2,3,Youssef Mohamed Kenawy,Youssef Mohamed Kenawy.pdf,84.75,67.49,GOOD MATCH
3,4,Hamza Ali Bakr,Hamza Ali Bakr.docx,79.50,65.25,GOOD MATCH
4,5,Marwa Ahmed Yehia Ibrahem,Marwa Ahmed Yehia Ibrahem.pdf,73.50,63.92,GOOD MATCH
5,6,Hazem Ismail Ismail Mostafa Zidan,Hazem Ismail Ismail Mostafa Zidan.pdf,77.25,63.59,GOOD MATCH
6,7,Marwan Montasser Morad Hassan,Marwan Montasser Morad Hassan.pdf,76.50,63.54,GOOD MATCH
7,8,Jomana Gehad Mohamed,Jomana Gehad Mohamed.docx,74.25,62.66,GOOD MATCH
8,9,Loai Farrag,Loai Farrag.docx,80.25,62.05,GOOD MATCH
9,10,Abdelrahman Mohamed Elkady,Abdelrahman Mohamed Elkady.pdf,75.75,61.43,GOOD MATCH

TOP 20

,rank,candidate_name,filename,ai_relevance_percent,final_match_percent,decision
0,1,Omar Mohamed,Omar Mohamed.pdf,81.75,68.97,GOOD MATCH
1,2,Salma Taha Abdelalem Eloraby,Salma Taha Abdelalem Eloraby.pdf,82.50,68.12,GOOD MATCH
2,3,Youssef Mohamed Kenawy,Youssef Mohamed Kenawy.pdf,84.75,67.49,GOOD MATCH
3,4,Hamza Ali Bakr,Hamza Ali Bakr.docx,79.50,65.25,GOOD MATCH
4,5,Marwa Ahmed Yehia Ibrahem,Marwa Ahmed Yehia Ibrahem.pdf,73.50,63.92,GOOD MATCH
5,6,Hazem Ismail Ismail Mostafa Zidan,Hazem Ismail Ismail Mostafa Zidan.pdf,77.25,63.59,GOOD MATCH
6,7,Marwan Montasser Morad Hassan,Marwan Montasser Morad Hassan.pdf,76.50,63.54,GOOD MATCH
7,8,Jomana Gehad Mohamed,Jomana Gehad Mohamed.docx,74.25,62.66,GOOD MATCH
8,9,Loai Farrag,Loai Farrag.docx,80.25,62.05,GOOD MATCH
9,10,Abdelrahman Mohamed Elkady,Abdelrahman Mohamed Elkady.pdf,75.75,61.43,GOOD MATCH
10,11,Raghad Mohamed Wael Khalil,Raghad Mohamed Wael Khalil.pdf,78.00,60.86,GOOD MATCH
11,12,Andrew Aziz,Andrew Aziz.pdf,69.75,58.97,WEAK MATCH
12,13,Abdulrahman wahba,Abdulrahman wahba.pdf,69.00,58.43,WEAK MATCH
13,14,Khaled Mahmoud Hamdi,Khaled Mahmoud Hamdi.pdf,68.25,58.42,WEAK MATCH
14,15,Karim Mohamed Abdelaziz Mokadem,Karim Mohamed Abdelaziz Mokadem.pdf,65.25,57.20,WEAK MATCH
15,16,Maged waleed,Maged waleed.pdf,61.50,57.07,WEAK MATCH
16,17,Marwan sherif saleh,Marwan sherif saleh.pdf,75.00,56.48,WEAK MATCH
17,18,Hazim Ashraf,Hazim Ashraf.pdf,68.25,55.53,WEAK MATCH
18,19,Youssef abdulazim,Youssef abdulazim.pdf,72.75,55.46,WEAK MATCH
19,20,Yusuf Adel Abbas Amin,Yusuf Adel Abbas Amin.pdf,65.25,54.96,WEAK MATCH

REJECTED CANDIDATES

,rank,candidate_name,filename,ai_relevance_percent,final_match_percent,decision
63,64,Omar Ahmed Abdelraouf,Omar Ahmed Abdelraouf.pdf,18.0,0.0,REJECT
64,65,Alaa Karam Ahmed Mohamed Salama,Alaa Karam Ahmed Mohamed Salama.pdf,15.0,0.0,REJECT
65,66,Habiba Tarek Maher,Habiba Tarek Maher.pdf,15.0,0.0,REJECT
66,67,Mohamed Hisham Wafa,Mohamed Hisham Wafa.docx,15.0,0.0,REJECT
67,68,Ahmed Maged Mounir Mohammed,Ahmed Maged Mounir Mohammed.pdf,12.0,0.0,REJECT
68,69,Ather Walid Abdel Wahed Abou Shama,Ather Walid Abdel Wahed Abou Shama.pdf,12.0,0.0,REJECT
69,70,Faten Shahir Shokry Negeida,Faten Shahir Shokry Negeida.pdf,12.0,0.0,REJECT
70,71,Mirna Hany,Mirna Hany.pdf,12.0,0.0,REJECT
71,72,Mohamed Mokhtar Shaker,Mohamed Mokhtar Shaker.pdf,12.0,0.0,REJECT
72,73,Natalia Ehab Habib,Natalia Ehab Habib.pdf,12.0,0.0,REJECT
73,74,Noor Omar Mohamed Elsamahy,Noor Omar Mohamed Elsamahy.docx,12.0,0.0,REJECT
74,75,Nour mohamed hassan,Nour mohamed hassan.pdf,12.0,0.0,REJECT
75,76,Sally Ahmed Mostafa Mohamed,Sally Ahmed Mostafa Mohamed.pdf,12.0,0.0,REJECT
76,77,Sherry Nabil Mahmoud,Sherry Nabil Mahmoud.pdf,12.0,0.0,REJECT
77,78,Youssef Mohammed Hussein sayed abdelalim,Youssef Mohammed Hussein sayed abdelalim.pdf,12.0,0.0,REJECT
78,79,ahmed mohamed ezzat,ahmed mohamed ezzat.pdf,12.0,0.0,REJECT
79,80,Mahmoud Samir Mahmoud Moustafa,Mahmoud Samir Mahmoud Moustafa.pdf,9.0,0.0,REJECT
80,81,Mariam Ahmed Bolbol,Mariam Ahmed Bolbol.pdf,6.0,0.0,REJECT
81,82,Amr karam alaasar,Amr karam alaasar.pdf,0.0,0.0,REJECT
82,83,Habiba Ahmed Aboelenen,Habiba Ahmed Aboelenen.pdf,0.0,0.0,REJECT
83,84,Hana hatem,Hana hatem.pdf,0.0,0.0,REJECT
84,85,Hassan Hossam eldain hassan,Hassan Hossam eldain hassan.docx,0.0,0.0,REJECT
85,86,Laila Bassem,Laila Bassem.pdf,0.0,0.0,REJECT
86,87,Marwan ahmed,Marwan ahmed.pdf,0.0,0.0,REJECT
87,88,Mohamed Ahmed Mohamed Abdelsamie Arid,Mohamed Ahmed Mohamed Abdelsamie Arid.pdf,0.0,0.0,REJECT
88,89,Mohanad tamer sabry,Mohanad tamer sabry.pdf,0.0,0.0,REJECT
89,90,Moustafa Hani Moustafa Mansour,Moustafa Hani Moustafa Mansour.pdf,0.0,0.0,REJECT
90,91,Nourine Hossam el deen mokhtar,Nourine Hossam el deen mokhtar.pdf,0.0,0.0,REJECT
91,92,Reham Sameh Sayed Kandeel,Reham Sameh Sayed Kandeel.pdf,0.0,0.0,REJECT
92,93,Seif Ahmed Ibrahim Eltahmoudi,Seif Ahmed Ibrahim Eltahmoudi.pdf,0.0,0.0,REJECT
93,94,Yassin Mohamed Amer,Yassin Mohamed Amer.docx,0.0,0.0,REJECT
94,95,Youssef abdelmesseh ramzy,Youssef abdelmesseh ramzy.pdf,0.0,0.0,REJECT
95,96,Zeyad Hesham Mohamed Hussein,Zeyad Hesham Mohamed Hussein.pdf,0.0,0.0,REJECT
96,97,mariam hatem,mariam hatem.pdf,0.0,0.0,REJECT
97,98,Omar Wael Hassan,Omar Wael Hassan.pdf,0.0,0.0,REJECT - FILE ERROR/EMPTY

## 10. Mass Communication Test

The following unrelated CV should fail the AI relevance gate and receive approximately 0% final match.

In [17]:
mass_communication_cv = """
Mass Communication student with experience in social media marketing,
content creation, public relations, advertising campaigns, and brand communication.
"""

test_ai_relevance = calculate_ai_relevance(mass_communication_cv)

test_rows = []
for req_key, req in JOB_REQUIREMENTS.items():
    score, matched = calculate_keyword_score(mass_communication_cv, req)
    test_rows.append({
        "Requirement": req["name"],
        "Keyword Score": round(score * 100, 2),
        "Matched Terms": ", ".join(matched) if matched else "Not Found"
    })

print("AI Relevance:", round(test_ai_relevance * 100, 2), "%")
display(pd.DataFrame(test_rows))

if test_ai_relevance < AI_RELEVANCE_THRESHOLD:
    print("FINAL MATCH: 0%")
    print("DECISION: REJECT")
else:
    print("Review the AI relevance signals: the synthetic test passed the gate.")

AI Relevance: 0.0 %

                                  Requirement  Keyword Score Matched Terms
0                             ML Fundamentals            0.0     Not Found
1  Model Training / Evaluation / Optimization            0.0     Not Found
2                        Hands-on AI Projects            0.0     Not Found
3                         Backend Development            0.0     Not Found
4                 REST APIs / FastAPI / Flask            0.0     Not Found
5           AI Model Integration / Deployment            0.0     Not Found

FINAL MATCH: 0%
DECISION: REJECT

## 11. Export Excel Report

In [18]:
output_path = "/content/AI_CV_Matching_Results.xlsx"

ranking_columns = [
    "rank", "candidate_name", "filename", "file_type",
    "processing_status", "ai_relevance_percent",
    "keyword_percent", "semantic_percent", "evidence_percent",
    "final_match_percent", "decision",
    "matched_skills", "missing_skills", "strong_evidence"
]

skill_columns = [
    col for col in results_df.columns
    if " - Keyword" in col or " - Semantic" in col or " - Evidence" in col
]

with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
    results_df[ranking_columns].to_excel(
        writer, sheet_name="Ranking", index=False
    )
    results_df[["rank", "candidate_name", "filename"] + skill_columns].to_excel(
        writer, sheet_name="Skill Analysis", index=False
    )
    rejected_df[ranking_columns].to_excel(
        writer, sheet_name="Rejected Candidates", index=False
    )
    results_df.head(TOP_N)[ranking_columns].to_excel(
        writer, sheet_name="Top Candidates", index=False
    )

print(f"Created: {output_path}")

Created: /content/AI_CV_Matching_Results.xlsx

## 12. Download Results

In [19]:
from google.colab import files

files.download("/content/AI_CV_Matching_Results.xlsx")